version: '3.8'

services:
  app1:
    image: volumetask:dev
    build:
      context: .
      dockerfile: VolumeTask/Dockerfile
    ports:
      - "5001:8080"
    volumes:
      - errorsvolume:/Logs
      - infovolume:/Logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  errorsvolume:
     external: true
  infovolume:
     external: true
